packages:
  - src/applications/*
  - src/libraries/*
catalog:
  effect: ^3.14.18
  "@effect/platform": ^0.80.18
  "@effect/platform-node": ^0.77.6
  "@effect/typeclass": ^0.33.18
  "@effect/cli": ^0.59.18
  "@effect/sql": "^0.33.18"
  "@effect/sql-drizzle": "^0.32.18"
  "@effect/sql-sqlite-node": "^0.34.18"
  "@effect/experimental": "^0.44.18"
  typescript: ^5.8.3
onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@prisma/client"
  - "@prisma/engines"
  - esbuild
  - msgpackr-extract
  - prisma
