packages:
  - src/applications/*
  - src/libraries/*
catalog:
  effect: ^3.14.14
  "@effect/platform": ^0.80.14
  "@effect/platform-node": ^0.77.2
  "@effect/typeclass": ^0.33.14
  "@effect/cli": ^0.59.14
  typescript: ^5.8.3
onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@prisma/client"
  - "@prisma/engines"
  - esbuild
  - msgpackr-extract
  - prisma
