packages:
  - src/applications/*
  - src/libraries/*
catalog:
  effect: ^3.14.11
  "@effect/platform": ^0.80.11
  "@effect/platform-node": ^0.76.21
  "@effect/typeclass": ^0.33.11
  "@effect/cli": ^0.59.11
  typescript: ^5.8.3
onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@prisma/client"
  - "@prisma/engines"
  - esbuild
  - msgpackr-extract
  - prisma
